### ISSUE TITLE
[ERROR]: Cannot create template: 404 ({"type":"NotFoundError","message":"CaseTemplate not found"})

### ISSUE THREAD

**Issue by pelaohcx** [emalderson/ThePhish#55]
**Work environment**

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        |    |
| OS version (client)        | Ubuntu 22.04.5            |
| Python version | Python 3.10.12 |
| Type of email address used | Gmail |
| Mail client type & version | Gmail. |
| Browser type & version     | Chrome Versión 130.0.6723.70 (Build oficial) (64 bits)  |
| Virtualized  Env.          | True                         |
| Dedicated RAM              | 16 GB                                 |
| vCPU                       |         4              |
| ThePhish version  |           |
| TheHive version  |           |
| Cortex version  |           |
| MISP version  |           |
| Installed using Docker and Docker Compose | True |
| Docker Version | Docker version 27.3.1, build ce12230 |
| Docker Compose version | Docker-compose version 1.29.2 |

when I scan an email I get the following error

[ERROR]_[case_from_email]: Cannot create template: 404 ({“type”: “NotFoundError”, “message”: “CaseTemplate not found”})
[ERROR]_[thephish_app]: Exception in /analysis [POST].
Traceback (last most recent call):
  File “/opt/ThePhish/app/venv/lib/python3.10/site-packages/flask/app.py”, line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File “/opt/ThePhish/app/venv/lib/python3.10/site-packages/flask/app.py”, line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File “/opt/ThePhish/app/venv/lib/python3.10/site-packages/flask/app.py”, line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File “/opt/ThePhish/app/venv/lib/python3.10/site-packages/flask/app.py”, line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File “/opt/ThePhish/app/thephish_app.py”, line 40, in analyze_email
    verdict = run_analysis.main(wsl, new_case_id, external_from_field)
  File “/opt/ThePhish/app/run_analysis.py”, line 558, in main
    tasks = api_thehive.get_case_tasks(case.json()['id']).json()
AttributeError: 'NoneType' object has no attribute 'json'.

![image](https://github.com/user-attachments/assets/a72cdbab-be4d-4f1e-b269-56739ca0fc93)

![image](https://github.com/user-attachments/assets/32b5351d-bb98-4b02-9ccf-6458466ede76)

**Comment by bartas1986** [comment]
```
[ERROR]_[case_from_email]: Cannot create template: 404 ({"type":"NotFoundError","message":"CaseTemplate not found"})
[ERROR]_[thephish_app]: Exception on /analysis [POST]
Traceback (most recent call last):
  File "/root/ThePhish/app/venv/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/ThePhish/app/venv/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/ThePhish/app/venv/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/ThePhish/app/venv/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/ThePhish/app/thephish_app.py", line 36, in analyze_email
    verdict = run_analysis.main(wsl, new_case_id, external_from_field)
  File "/root/ThePhish/app/run_analysis.py", line 556, in main
    tasks = api_thehive.get_case_tasks(case.json()['id']).json()
AttributeError: 'NoneType' object has no attribute 'json'
```
I get the same error message, was this resolved or did you find where the error occurs?
